/**:

  ros__parameters:
  
    communication:
      bridge_port: 1235
      fsw_port: 1234	
      fsw_ip: "127.0.0.1"

    cfdp:

      ip: "127.0.0.1"
      port:  5222
      entity_id: 2


      ip_peer: "127.0.0.1"
      port_peer:  5111
      entity_id_peer: 1
            
      store_package:  "data_transfer"
      store_folder: "data/remote"
  
    write_data: ['tlm_depth_haz', 'tlm_cam_nav']
#    read_data: []
# Storing data

    tlm_depth_haz:
      type: "sensor_msgs/msg/PointCloud2"
      topic: "/hw/depth_haz/points"
      rate:  5000 # 2seconds = 2000 ms
      store_pkg: "data_transfer"
      store_filename: "data/remote/depth_haz"
      
    tlm_cam_nav:
      type: "sensor_msgs/msg/Image"
      topic: "/hw/cam_nav"
      rate: 3000
      store_pkg: "data_transfer"
      store_filename: "data/remote/cam_nav"

# Retrieving data

#    rx_scan_1:
#      type: "sensor_msgs/msg/LaserScan"
#      topic: "/rx/robot_1/scan"
#      rate:  1000
#      store_pkg: "data_transfer"
#      store_filename: "data/rcv/scan_1"

