conversion_node:

  ros__parameters:
  
    communication:
      bridge_port: 1235
      fsw_port: 1234
      fsw_ip: "127.0.0.1"
      telemetry_ip: "0.0.0.0"

      # Phase I helper
      bridge_ip: "127.0.0.1" # IP of the machine where this bridge is running
  
    command: ['pose_cmd_1', 'pose_cmd_2']
    telemetry: ['js_tlm_1', 'js_tlm_2']

    pose_cmd_1:
      type: "geometry_msgs/msg/Pose"
      topic: "/big_arm/ground/target"
      mid: 0x1827 # EDORAS_APP_CMD_1_GROUND_MID 
      
    pose_cmd_2:
      type: "geometry_msgs/msg/Pose"
      topic: "/little_arm/ground/target"
      mid: 0x1828 # EDORAS_APP_CMD_2_GROUND_MID

    js_tlm_1:
      type: "sensor_msgs/msg/JointState"
      topic: "/big_arm/ground/joint_states"
      mid: 0x828 # EDORAS_APP_TLM_1_GROUND_MID

    js_tlm_2:
      type: "sensor_msgs/msg/JointState"
      topic: "/little_arm/ground/joint_states"
      mid: 0x829 # EDORAS_APP_TLM_2_GROUND_MID
