ground_conversion_node:

  ros__parameters:
  
    communication:
      bridge_port: 1235 # udp_receive_port in brash
      fsw_port: 1235 # 1234 for cpu1 (singlehost) or 1235 for cpu2 (multihost)	
      fsw_ip: "192.168.6.60" # 127.0.0.1 (udp_command_ip in brash)
      telemetry_ip: "0.0.0.0"   # Means open to communicate with all (udp_send_port in brash)

      # Phase I helper
      # This is used to tell TO Lab to send telemetry data back to this machine
      bridge_ip: "192.168.7.208" # IP of the machine where the ground bridge is running
  
    command: ['cmd_twist']
    telemetry: ['tlm_pose']

    cmd_twist:
      type: "geometry_msgs/msg/Twist"
      topic: "command_twist"
      mid: 0x1827 # GATEWAY_APP_CMD_MID 

    tlm_pose:
      type: "geometry_msgs/msg/PoseStamped"
      topic: "telemetry_pose"
      mid: 0x827 # GATEWAY_APP_TLM_MID
