ground_conversion_node:

  ros__parameters:
  
    communication:
      bridge_port: 1235
      fsw_port: 1234	
      fsw_ip: "127.0.0.1"
      telemetry_ip: "0.0.0.0"

      # Phase I helper
      bridge_ip: "127.0.0.1"
  
    command: ['pose_to_fsw']
    telemetry: ['twist_to_robot']

    pose_to_fsw:
      type: "geometry_msgs/msg/PoseStamped"
      topic: "robot_1/telemetry_pose"
      mid: 0x827 # GATEWAY_APP_TLM_MID
      
    twist_to_robot:
      type: "geometry_msgs/msg/Twist"
      topic: "/robot_1/cmd_vel"
      mid: 0x1827 # GATEWAY_APP_CMD_MID 
      
