conversion_node:

  ros__parameters:
  
    communication:
      bridge_port: 1235
      fsw_port: 1234
      fsw_ip: "127.0.0.1"
      telemetry_ip: "0.0.0.0"

      # Phase I helper
      bridge_ip: "127.0.0.1" # IP of the machine where this bridge is running
  
    command: ['twist_cmd_1', 'twist_cmd_2']
    telemetry: ['pose_tlm_1', 'pose_tlm_2']

    twist_cmd_1:
      type: "geometry_msgs/msg/Twist"
      topic: "/robot_1/ground/cmd_vel"
      mid: 0x1827 # EDORAS_APP_TWIST_1_GROUND_MID 
      
    twist_cmd_2:
      type: "geometry_msgs/msg/Twist"
      topic: "/robot_2/ground/cmd_vel"
      mid: 0x1828 # EDORAS_APP_TWIST_2_GROUND_MID

    pose_tlm_1:
      type: "geometry_msgs/msg/PoseStamped"
      topic: "/robot_1/ground/pose"
      mid: 0x828 # EDORAS_APP_POSE_1_GROUND_MID

    pose_tlm_2:
      type: "geometry_msgs/msg/PoseStamped"
      topic: "/robot_2/ground/pose"
      mid: 0x829 # EDORAS_APP_POSE_2_GROUND_MID
